"""Add width, height, filesize, mime_type to Item model

Revision ID: 4dead0543945
Revises: 90c7e3431e9d
Create Date: 2025-04-22 18:19:02.924587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dead0543945'
down_revision = '90c7e3431e9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('filesize', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mime_type', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('mime_type')
        batch_op.drop_column('filesize')
        batch_op.drop_column('height')
        batch_op.drop_column('width')

    # ### end Alembic commands ###
